/*
 * www.akuacom.com - Automating Demand Response
 * 
 * services.web.bacnet.BacnetPortType.java - Copyright(c)1994 to 2010 by Akuacom . All rights reserved. 
 * Redistribution and use in source and binary forms, with or without modification, is prohibited.
 *
 */

package services.web.bacnet;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 */
@WebService(name = "bacnetPortType", targetNamespace = "urn:bacnet-web-services")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BacnetPortType {


    /**
     * Service definition of function ns__getValue.
     * 
     * @param path the path
     * @param options the options
     * 
     * @return the value
     * 
     * returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public String getValue(
        @WebParam(name = "options", partName = "options")
        String options,
        @WebParam(name = "path", partName = "path")
        String path);

    /**
     * Service definition of function ns__setValue.
     * 
     * @param value the value
     * @param path the path
     * @param options the options
     * 
     * @return the string
     * 
     * returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public String setValue(
        @WebParam(name = "options", partName = "options")
        String options,
        @WebParam(name = "path", partName = "path")
        String path,
        @WebParam(name = "value", partName = "value")
        String value);

    /**
     * Service definition of function ns__getDefaultLocale.
     * 
     * @param options the options
     * 
     * @return the default locale
     * 
     * returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public String getDefaultLocale(
        @WebParam(name = "options", partName = "options")
        String options);

    /**
     * Service definition of function ns__getSupportedLocals.
     * 
     * @param options the options
     * 
     * @return the supported locals
     * 
     * returns services.web.bacnet.ArrayOfstring
     */
    @WebMethod
    @WebResult(name = "results", partName = "results")
    public ArrayOfstring getSupportedLocals(
        @WebParam(name = "options", partName = "options")
        String options);

}
