/*
 * www.akuacom.com - Automating Demand Response
 * 
 * services.web.bacnet.Bacnet.java - Copyright(c)1994 to 2010 by Akuacom . All rights reserved. 
 * Redistribution and use in source and binary forms, with or without modification, is prohibited.
 *
 */

package services.web.bacnet;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * DRAS bacnet
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 */
@WebServiceClient(name = "bacnet", targetNamespace = "urn:bacnet-web-services", wsdlLocation = "file:/C:/dev/pss2-core-all/pss2.clientws.bacnet.stubs/BACnetClientWS.wsdl")
public class Bacnet
    extends Service
{

    /** The Constant BACNET_WSDL_LOCATION. */
    private final static URL BACNET_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/dev/pss2-core-all/pss2.clientws.bacnet.stubs/BACnetClientWS.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        BACNET_WSDL_LOCATION = url;
    }

    /**
     * Instantiates a new bacnet.
     * 
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     */
    public Bacnet(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Instantiates a new bacnet.
     */
    public Bacnet() {
        super(BACNET_WSDL_LOCATION, new QName("urn:bacnet-web-services", "bacnet"));
    }

    /**
     * Gets the bacnet.
     * 
     * @return the bacnet
     * 
     * returns BacnetPortType
     */
    @WebEndpoint(name = "bacnet")
    public BacnetPortType getBacnet() {
        return (BacnetPortType)super.getPort(new QName("urn:bacnet-web-services", "bacnetPortType"), BacnetPortType.class);
    }

}
