/**
 * 
 */
package com.akuacom.pss2.drw.model;


/**
 * the enum CacheCatogary
 * 
 */
public enum CacheCategory {
	SAI_RESIDENTIAL_ACTIVE,
	SAI_RESIDENTIAL_SCHEDULED,
	
	SPD_RESIDENTIAL_ACTIVE,
	SPD_RESIDENTIAL_SCHEDULED,

	
	SAI_COMMERCIAL_ACTIVE,
	SAI_COMMERCIAL_SCHEDULED,

	DBP_COMMERCIAL_ACTIVE,
	DBP_COMMERCIAL_SCHEDULED,

	DRC_COMMERCIAL_ACTIVE,
	DRC_COMMERCIAL_SCHEDULED,
	
	RTP_FORCAST,
	
	KIOSK_ACTIVE,
	KIOSK_SCHEDULED,
	
	ACT_SDPRESI_EVENT,
	ACT_SDPCOME_EVENT,
	ACT_API_EVENT,
	ACT_BIP_EVENT,
	ACT_CBP_EVENT,
	SCHE_SDPRESI_EVENT,
	SCHE_SDPCOME_EVENT,
	SCHE_API_EVENT,
	SCHE_BIP_EVENT,
	SCHE_CBP_EVENT,
	
	LOCATION
}
