/*
 * www.akuacom.com - Automating Demand Response
 * 
 * org.openadr.dras.akuautilityoperator.AkuaUtilityOperatorService.java - Copyright(c)1994 to 2010 by Akuacom . All rights reserved. 
 * Redistribution and use in source and binary forms, with or without modification, is prohibited.
 *
 */

package org.openadr.dras.akuautilityoperator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 */
@WebServiceClient(name = "AkuaUtilityOperatorService", targetNamespace = "http://www.openadr.org/DRAS/AkuaUtilityOperator/", wsdlLocation = "file:/C:/bin/pss2-4.3/pss2.utilopws.stubs/AkuaUtilityOperator.wsdl")
public class AkuaUtilityOperatorService
    extends Service
{

    /** The Constant AKUAUTILITYOPERATORSERVICE_WSDL_LOCATION. */
    private final static URL AKUAUTILITYOPERATORSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/bin/pss2-4.3/pss2.utilopws.stubs/AkuaUtilityOperator.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        AKUAUTILITYOPERATORSERVICE_WSDL_LOCATION = url;
    }

    /**
     * Instantiates a new akua utility operator service.
     * 
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     */
    public AkuaUtilityOperatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Instantiates a new akua utility operator service.
     */
    public AkuaUtilityOperatorService() {
        super(AKUAUTILITYOPERATORSERVICE_WSDL_LOCATION, new QName("http://www.openadr.org/DRAS/AkuaUtilityOperator/", "AkuaUtilityOperatorService"));
    }

    /**
     * Gets the akua utility operator port.
     * 
     * @return the akua utility operator port
     * 
     * returns AkuaUtilityOperator
     */
    @WebEndpoint(name = "AkuaUtilityOperatorPort")
    public AkuaUtilityOperator getAkuaUtilityOperatorPort() {
        return (AkuaUtilityOperator)super.getPort(new QName("http://www.openadr.org/DRAS/AkuaUtilityOperator/", "AkuaUtilityOperatorPort"), AkuaUtilityOperator.class);
    }

}
