update event set programName = 'SAI' where programName = 'CPP';
update bid_level_mapping set programName = 'SAI' where programName = 'CPP';
update client_conversation_state set programName = 'SAI' where programName = 'CPP';
update contacts_offline_error set programName = 'SAI' where programName = 'CPP';
update event_template set programName = 'SAI' where programName = 'CPP';
update history_event set programName = 'SAI' where programName = 'CPP';
update message set programName = 'SAI' where programName = 'CPP';
update peakchoice_message set programName = 'SAI' where programName = 'CPP';
update rtp_remote_price set programName = 'SAI' where programName = 'CPP';
update program_participant set programName = 'SAI' where programName = 'CPP';
update report_event set programName = 'SAI' where programName = 'CPP';
update report_event_participation set programName = 'SAI' where programName = 'CPP';
update report_event_signal set programName = 'SAI' where programName = 'CPP';
update program set name = 'SAI', longProgramName = 'SAI', utilityProgramName = 'SAI' where name = 'CPP';
