
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'SPECIAL','tariff_limit','EQUAL','0','Demand Limiting Participant','0','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'NA','0','0');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'SPECIAL','rate_interval','EQUAL','15','Demand Limiting','1','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'NA','0','0');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'SPECIAL','meter_interval','EQUAL','5','Demand Limiting','2','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'NA','0','0');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'SPECIAL','event_span','EQUAL','10','Demand Limiting','3','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'NA','0','0');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'SPECIAL','interval_load','EQUAL','0','Telemetry','4','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'NA','0','0');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'SPECIAL','meter_timestamp','EQUAL','0','Telemetry','5','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'NA','0','0');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'SPECIAL','threshold_percentage','EQUAL','0','Telemetry','6','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'NA','0','0');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'SPECIAL','warning','EQUAL','0','Telemetry','7','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'NA','0','0');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'NORMAL','threshold_percentage','LESS_THAN','75','Demand Limiting Percentage','8','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'normal','0','0');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'NORMAL','threshold_percentage','GREATER_THAN_OR_EQUAL','75','Demand Limiting Percentage','9','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'warning','1','0');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'MODERATE','threshold_percentage','GREATER_THAN_OR_EQUAL','80','Demand Limiting Percentage','10','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'moderate','1','1');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'HIGH','threshold_percentage','GREATER_THAN_OR_EQUAL','95','Demand Limiting Percentage','11','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'high','1','1');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'HIGH','threshold_percentage','GREATER_THAN_OR_EQUAL','100','Demand Limiting Percentage','12','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'exceeded','1','1');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'NORMAL','interval_load','LESS_THAN','0','Demand Limiting Load','13','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'normal','0','0');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'NORMAL','interval_load','GREATER_THAN_OR_EQUAL','0','Demand Limiting Load','14','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'warning','1','0');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'MODERATE','interval_load','GREATER_THAN_OR_EQUAL','0','Demand Limiting Load','15','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'moderate','1','1');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'HIGH','interval_load','GREATER_THAN_OR_EQUAL','0','Demand Limiting Load','16','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'high','1','1');
INSERT INTO `program_rule` (`uuid`, `start`, `end`, `mode`, `variable`, `operator`, `value`, `source`, `sortOrder`, `version`, `creator`, `modifier`, `creationTime`, `modifiedTime`, `program_uuid`, `threshold`, `notifyAction`, `signalAction`) 
VALUES(REPLACE(uuid(), '-', ''),'2012-01-03 10:55:30',NULL,'HIGH','interval_load','GREATER_THAN_OR_EQUAL','0','Demand Limiting Load','17','0','script',NULL,'2012-01-03 10:55:30',NULL,(SELECT uuid from program where name = 'Demand Limiting Program'),'exceeded','1','1');
