#!/bin/bash
scala -classpath \
common/util/target/classes:\
common/util-ejb/target/classes:\
common/util-ejb/target/test-classes:\
drms/core/drms-core/target/classes:\
drms/core/drms-core-ejb/target/classes:\
drms/lib/drms-util/target/classes:\
drms/lib/util-op-common/target/classes:\
drms/web/facility-web/target/classes:\
drms/web/rich-web/target/classes:\
drms/web/struts-web/target/classes:\
drms/web/facility-web/target/classes:\
drms/ws/adx-sdg-cbp/target/classes:\
drms/ws/akua-util-op/target/classes:\
drms/ws/bacnet/target/classes:\
drms/ws/data/target/classes:\
drms/ws/itron-pge-dbp-in/target/classes:\
drms/ws/legacy/target/classes:\
drms/ws/obix-rest/target/classes:\
drms/ws/part-data/target/classes:\
drms/ws/part-op/target/classes:\
drms/ws/plp/target/classes:\
drms/ws/rest/target/classes:\
drms/ws/rest-util-op/target/classes:\
drms/ws/soap/target/classes:\
drms/ws/util-op/target/classes:\
drms/ws-client/ads-client/target/classes:\
drms/ws-client/bacnet-client/target/classes:\
drms/ws-client/data-client/target/classes:\
drms/ws-client/ieso-client/target/classes:\
drms/ws-client/legacy-client/target/classes:\
drms/ws-client/oasis-client/target/classes:\
drms/ws-client/obix-client/target/classes:\
drms/ws-client/part-data-client/target/classes:\
drms/ws-client/rest-client/target/classes:\
drms/ws-client/soap-client/target/classes:\
drms/ws-client/util-op-client/target/classes:\
drms/system/configure/lib/*.jar:\
drms/system/ear/drms-ear-test/target/test-classes:\
/home/ramdisk/m2/repository/org/hibernate/hibernate-annotations/3.4.0.GA/hibernate-annotations-3.4.0.GA.jar.jar:\
$M2_REPO/javax/persistence/persistence-api/1.0/persistence-api-1.0.jar:\
$M2_REPO/org/jboss/embedded/jboss-embedded/beta3/jboss-embedded-beta3.jar:\
$M2_REPO/org/jboss/embedded/jboss-embedded-all/beta3/jboss-embedded-all-beta3.jar:\
$M2_REPO/org/jboss/embedded/thirdparty-all/beta3/thirdparty-all-beta3.jar:\
$M2_REPO/org/aspectj/aspectjrt/1.6.10/aspectjrt-1.6.10.jar:\
$M2_REPO/log4j/log4j/1.2.15/log4j-1.2.15.jar:\
$M2_REPO/junit/junit/4.8.1/junit-4.8.1.jar

  
