package com.honeywell.dras.ge;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-24T11:44:56.937+05:30
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "ENMAC/ADR", name = "ADRSoap")
public interface ADRSoap {

    @WebResult(name = "AdrEventResponseStc", targetNamespace = "ENMAC/ADR")
    @RequestWrapper(localName = "SubmitADREvent", targetNamespace = "ENMAC/ADR", className = "com.honeywell.dras.ge.SubmitADREvent")
    @WebMethod(operationName = "SubmitADREvent", action = "ENMAC/ADR/SubmitADREvent")
    @ResponseWrapper(localName = "SubmitADREventResponse", targetNamespace = "ENMAC/ADR", className = "com.honeywell.dras.ge.SubmitADREventResponse")
    public com.honeywell.dras.ge.AdrEventResponseStc submitADREvent(
        @WebParam(name = "AdrEventStc", targetNamespace = "ENMAC/ADR")
        com.honeywell.dras.ge.AdrEventStc adrEventStc
    );
}
