/*
 * www.akuacom.com - Automating Demand Response
 * 
 * org.openadr.dras.drasclientsoap.DRASClientSOAP.java - Copyright(c)1994 to 2010 by Akuacom . All rights reserved. 
 * Redistribution and use in source and binary forms, with or without modification, is prohibited.
 *
 */

package org.openadr.dras.drasclientsoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.openadr.dras.eventstate.EventStateConfirmation;
import org.openadr.dras.eventstate.ListOfEventStates;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 */
@WebService(name = "DRASClientSOAP", targetNamespace = "http://www.openadr.org/DRAS/DRASClientSOAP/")
public interface DRASClientSOAP {


    /**
     * Gets the event states.
     * 
     * @param returnValue the return value
     * @param empty the empty
     * @param eventStates the event states
     */
    @WebMethod(operationName = "GetEventStates", action = "http://www.openadr.org/DRAS/DRASClientSOAP/GetEventStates")
    @RequestWrapper(localName = "GetEventStates", targetNamespace = "http://www.openadr.org/DRAS/DRASClientSOAP/", className = "org.openadr.dras.drasclientsoap.GetEventStates")
    @ResponseWrapper(localName = "GetEventStatesResponse", targetNamespace = "http://www.openadr.org/DRAS/DRASClientSOAP/", className = "org.openadr.dras.drasclientsoap.GetEventStatesResponse")
    public void getEventStates(
        @WebParam(name = "empty", targetNamespace = "")
        Object empty,
        @WebParam(name = "returnValue", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> returnValue,
        @WebParam(name = "eventStates", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ListOfEventStates> eventStates);

    /**
     * Sets the event state confirmation.
     * 
     * @param eventStateConfirmation the event state confirmation
     * 
     * @return the string
     * 
     * returns java.lang.String
     */
    @WebMethod(operationName = "SetEventStateConfirmation", action = "http://www.openadr.org/DRAS/DRASClientSOAP/SetEventStateConfirmation")
    @WebResult(name = "returnValue", targetNamespace = "")
    @RequestWrapper(localName = "SetEventStateConfirmation", targetNamespace = "http://www.openadr.org/DRAS/DRASClientSOAP/", className = "org.openadr.dras.drasclientsoap.SetEventStateConfirmation")
    @ResponseWrapper(localName = "SetEventStateConfirmationResponse", targetNamespace = "http://www.openadr.org/DRAS/DRASClientSOAP/", className = "org.openadr.dras.drasclientsoap.SetEventStateConfirmationResponse")
    public String setEventStateConfirmation(
        @WebParam(name = "eventStateConfirmation", targetNamespace = "")
        EventStateConfirmation eventStateConfirmation);

}
