/*
 * www.akuacom.com - Automating Demand Response
 * 
 * org.openadr.dras.drasclientsoap.DRASClientSOAP_Service.java - Copyright(c)1994 to 2010 by Akuacom . All rights reserved. 
 * Redistribution and use in source and binary forms, with or without modification, is prohibited.
 *
 */

package org.openadr.dras.drasclientsoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 */
@WebServiceClient(name = "DRASClientSOAP", targetNamespace = "http://www.openadr.org/DRAS/DRASClientSOAP/", wsdlLocation = "file:/C:/dev/pss2-core-all/pss2.clientws.soap.stubs/DRASClientSOAP.wsdl")
public class DRASClientSOAP_Service
    extends Service
{

    /** The Constant DRASCLIENTSOAP_WSDL_LOCATION. */
    private final static URL DRASCLIENTSOAP_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/dev/pss2-core-all/pss2.clientws.soap.stubs/DRASClientSOAP.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        DRASCLIENTSOAP_WSDL_LOCATION = url;
    }

    /**
     * Instantiates a new dRAS client soa p_ service.
     * 
     * @param wsdlLocation the wsdl location
     * @param serviceName the service name
     */
    public DRASClientSOAP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Instantiates a new dRAS client soa p_ service.
     */
    public DRASClientSOAP_Service() {
        super(DRASCLIENTSOAP_WSDL_LOCATION, new QName("http://www.openadr.org/DRAS/DRASClientSOAP/", "DRASClientSOAP"));
    }

    /**
     * Gets the dras client soap port.
     * 
     * @return the DRAS client soap port
     * 
     * returns DRASClientSOAP
     */
    @WebEndpoint(name = "DRASClientSOAPPort")
    public DRASClientSOAP getDRASClientSOAPPort() {
        return (DRASClientSOAP)super.getPort(new QName("http://www.openadr.org/DRAS/DRASClientSOAP/", "DRASClientSOAPPort"), DRASClientSOAP.class);
    }

}
