CREATE TABLE `zip_to_location_temp` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `SUBSTATION_NUM` VARCHAR(25) DEFAULT NULL,
  `SUB_NAME` VARCHAR(255) DEFAULT NULL,
  `MAILING_CITY_NAME` VARCHAR(255) DEFAULT NULL,
  `ZIP_CODE` VARCHAR(25) DEFAULT NULL,
  `COUNTY_NO` VARCHAR(25) DEFAULT NULL,
  `COUNTY_NAM` VARCHAR(255) DEFAULT NULL,
  `Block` VARCHAR(25) DEFAULT NULL,
  `slap_id` VARCHAR(25) DEFAULT NULL,
  `slap_name` VARCHAR(50) DEFAULT NULL,
  `a_bank_no` VARCHAR(25) DEFAULT NULL,
  `a_bank_name` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;