/*
 * www.akuacom.com - Automating Demand Response
 * 
 * com.akuacom.pss2.restapi.stubs.Destinations.java - Copyright(c)1994 to 2010 by Akuacom . All rights reserved. 
 * Redistribution and use in source and binary forms, with or without modification, is prohibited.
 *
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.30 at 05:24:01 PM PST 
//


package com.akuacom.pss2.restapi.stubs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openadr.dras.drasclient.Location;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="participants" minOccurs="0">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="participantID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;element name="groups" minOccurs="0">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="groupID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;element name="locations" minOccurs="0">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="location" type="{http://www.openadr.org/DRAS/DRASClient}Location"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;element name="drasClients" minOccurs="0">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="drasClientID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;/sequence>
 * &lt;attribute name="transactionID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "participants",
    "groups",
    "locations",
    "drasClients"
})
@XmlRootElement(name = "destinations")
public class Destinations {

    /** The participants. */
    @XmlElementRef(name = "participants", namespace = "http://www.openadr.org/DRAS/UtilityDREvent", type = JAXBElement.class)
    protected JAXBElement<Destinations.Participants> participants;
    
    /** The groups. */
    @XmlElementRef(name = "groups", namespace = "http://www.openadr.org/DRAS/UtilityDREvent", type = JAXBElement.class)
    protected JAXBElement<Destinations.Groups> groups;
    
    /** The locations. */
    @XmlElementRef(name = "locations", namespace = "http://www.openadr.org/DRAS/UtilityDREvent", type = JAXBElement.class)
    protected JAXBElement<Destinations.Locations> locations;
    
    /** The dras clients. */
    @XmlElementRef(name = "drasClients", namespace = "http://www.openadr.org/DRAS/UtilityDREvent", type = JAXBElement.class)
    protected JAXBElement<Destinations.DrasClients> drasClients;
    
    /** The transaction id. */
    @XmlAttribute(required = true)
    protected String transactionID;

    /**
     * Gets the value of the participants property.
     * 
     * @return the participants
     * 
     * possible object is
     * {@link JAXBElement }{@code <}{@link Destinations.Participants }{@code >}
     */
    public JAXBElement<Destinations.Participants> getParticipants() {
        return participants;
    }

    /**
     * Sets the value of the participants property.
     * 
     * @param value allowed object is
     * {@link JAXBElement }{@code <}{@link Destinations.Participants }{@code >}
     */
    public void setParticipants(JAXBElement<Destinations.Participants> value) {
        this.participants = ((JAXBElement<Destinations.Participants> ) value);
    }

    /**
     * Gets the value of the groups property.
     * 
     * @return the groups
     * 
     * possible object is
     * {@link JAXBElement }{@code <}{@link Destinations.Groups }{@code >}
     */
    public JAXBElement<Destinations.Groups> getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value allowed object is
     * {@link JAXBElement }{@code <}{@link Destinations.Groups }{@code >}
     */
    public void setGroups(JAXBElement<Destinations.Groups> value) {
        this.groups = ((JAXBElement<Destinations.Groups> ) value);
    }

    /**
     * Gets the value of the locations property.
     * 
     * @return the locations
     * 
     * possible object is
     * {@link JAXBElement }{@code <}{@link Destinations.Locations }{@code >}
     */
    public JAXBElement<Destinations.Locations> getLocations() {
        return locations;
    }

    /**
     * Sets the value of the locations property.
     * 
     * @param value allowed object is
     * {@link JAXBElement }{@code <}{@link Destinations.Locations }{@code >}
     */
    public void setLocations(JAXBElement<Destinations.Locations> value) {
        this.locations = ((JAXBElement<Destinations.Locations> ) value);
    }

    /**
     * Gets the value of the drasClients property.
     * 
     * @return the dras clients
     * 
     * possible object is
     * {@link JAXBElement }{@code <}{@link Destinations.DrasClients }{@code >}
     */
    public JAXBElement<Destinations.DrasClients> getDrasClients() {
        return drasClients;
    }

    /**
     * Sets the value of the drasClients property.
     * 
     * @param value allowed object is
     * {@link JAXBElement }{@code <}{@link Destinations.DrasClients }{@code >}
     */
    public void setDrasClients(JAXBElement<Destinations.DrasClients> value) {
        this.drasClients = ((JAXBElement<Destinations.DrasClients> ) value);
    }

    /**
     * Gets the value of the transactionID property.
     * 
     * @return the transaction id
     * 
     * possible object is
     * {@link String }
     */
    public String getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setTransactionID(String value) {
        this.transactionID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="drasClientID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     * &lt;/sequence>
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "drasClientID"
    })
    public static class DrasClients {

        /** The dras client id. */
        @XmlElement(required = true, nillable = true)
        protected String drasClientID;

        /**
         * Gets the value of the drasClientID property.
         * 
         * @return the dras client id
         * 
         * possible object is
         * {@link String }
         */
        public String getDrasClientID() {
            return drasClientID;
        }

        /**
         * Sets the value of the drasClientID property.
         * 
         * @param value allowed object is
         * {@link String }
         */
        public void setDrasClientID(String value) {
            this.drasClientID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="groupID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     * &lt;/sequence>
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "groupID"
    })
    public static class Groups {

        /** The group id. */
        @XmlElement(nillable = true)
        protected List<String> groupID;

        /**
         * Gets the value of the groupID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the groupID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         * getGroupID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * @return the group id
         */
        public List<String> getGroupID() {
            if (groupID == null) {
                groupID = new ArrayList<String>();
            }
            return this.groupID;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="location" type="{http://www.openadr.org/DRAS/DRASClient}Location"/>
     * &lt;/sequence>
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "location"
    })
    public static class Locations {

        /** The location. */
        @XmlElement(required = true, nillable = true)
        protected Location location;

        /**
         * Gets the value of the location property.
         * 
         * @return the location
         * 
         * possible object is
         * {@link Location }
         */
        public Location getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value allowed object is
         * {@link Location }
         */
        public void setLocation(Location value) {
            this.location = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="participantID" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     * &lt;/sequence>
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "participantID"
    })
    public static class Participants {

        /** The participant id. */
        @XmlElement(nillable = true)
        protected List<String> participantID;

        /**
         * Gets the value of the participantID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the participantID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         * getParticipantID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * @return the participant id
         */
        public List<String> getParticipantID() {
            if (participantID == null) {
                participantID = new ArrayList<String>();
            }
            return this.participantID;
        }

    }

}
