/*
 * www.akuacom.com - Automating Demand Response
 * 
 * com.akuacom.pss2.restapi.stubs.ObjectFactory.java - Copyright(c)1994 to 2010 by Akuacom . All rights reserved. 
 * Redistribution and use in source and binary forms, with or without modification, is prohibited.
 *
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.30 at 05:24:01 PM PST 
//


package com.akuacom.pss2.restapi.stubs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.akuacom.pss2.restapi.stubs package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    /** The Constant _DestinationsLocations_QNAME. */
    private final static QName _DestinationsLocations_QNAME = new QName("http://www.openadr.org/DRAS/UtilityDREvent", "locations");
    
    /** The Constant _DestinationsDrasClients_QNAME. */
    private final static QName _DestinationsDrasClients_QNAME = new QName("http://www.openadr.org/DRAS/UtilityDREvent", "drasClients");
    
    /** The Constant _DestinationsGroups_QNAME. */
    private final static QName _DestinationsGroups_QNAME = new QName("http://www.openadr.org/DRAS/UtilityDREvent", "groups");
    
    /** The Constant _DestinationsParticipants_QNAME. */
    private final static QName _DestinationsParticipants_QNAME = new QName("http://www.openadr.org/DRAS/UtilityDREvent", "participants");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.akuacom.pss2.restapi.stubs
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Destinations.DrasClients }
     * 
     * @return the dras clients
     */
    public Destinations.DrasClients createDestinationsDrasClients() {
        return new Destinations.DrasClients();
    }

    /**
     * Create an instance of {@link Destinations }.
     * 
     * @return the destinations
     */
    public Destinations createDestinations() {
        return new Destinations();
    }

    /**
     * Create an instance of {@link Destinations.Locations }
     * 
     * @return the locations
     */
    public Destinations.Locations createDestinationsLocations() {
        return new Destinations.Locations();
    }

    /**
     * Create an instance of {@link Destinations.Participants }
     * 
     * @return the participants
     */
    public Destinations.Participants createDestinationsParticipants() {
        return new Destinations.Participants();
    }

    /**
     * Create an instance of {@link Destinations.Groups }
     * 
     * @return the groups
     */
    public Destinations.Groups createDestinationsGroups() {
        return new Destinations.Groups();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Destinations.Locations }{@code >}}
     * 
     * @param value the value
     * 
     * @return the JAXB element< destinations. locations>
     */
    @XmlElementDecl(namespace = "http://www.openadr.org/DRAS/UtilityDREvent", name = "locations", scope = Destinations.class)
    public JAXBElement<Destinations.Locations> createDestinationsLocations(Destinations.Locations value) {
        return new JAXBElement<Destinations.Locations>(_DestinationsLocations_QNAME, Destinations.Locations.class, Destinations.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Destinations.DrasClients }{@code >}}
     * 
     * @param value the value
     * 
     * @return the JAXB element< destinations. dras clients>
     */
    @XmlElementDecl(namespace = "http://www.openadr.org/DRAS/UtilityDREvent", name = "drasClients", scope = Destinations.class)
    public JAXBElement<Destinations.DrasClients> createDestinationsDrasClients(Destinations.DrasClients value) {
        return new JAXBElement<Destinations.DrasClients>(_DestinationsDrasClients_QNAME, Destinations.DrasClients.class, Destinations.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Destinations.Groups }{@code >}}
     * 
     * @param value the value
     * 
     * @return the JAXB element< destinations. groups>
     */
    @XmlElementDecl(namespace = "http://www.openadr.org/DRAS/UtilityDREvent", name = "groups", scope = Destinations.class)
    public JAXBElement<Destinations.Groups> createDestinationsGroups(Destinations.Groups value) {
        return new JAXBElement<Destinations.Groups>(_DestinationsGroups_QNAME, Destinations.Groups.class, Destinations.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Destinations.Participants }{@code >}}
     * 
     * @param value the value
     * 
     * @return the JAXB element< destinations. participants>
     */
    @XmlElementDecl(namespace = "http://www.openadr.org/DRAS/UtilityDREvent", name = "participants", scope = Destinations.class)
    public JAXBElement<Destinations.Participants> createDestinationsParticipants(Destinations.Participants value) {
        return new JAXBElement<Destinations.Participants>(_DestinationsParticipants_QNAME, Destinations.Participants.class, Destinations.class, value);
    }

}
