/*
 * www.akuacom.com - Automating Demand Response
 * 
 * com.akuacom.pss2.restapi.stubs.package-info.java - Copyright(c)1994 to 2010 by Akuacom . All rights reserved. 
 * Redistribution and use in source and binary forms, with or without modification, is prohibited.
 *
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.30 at 05:24:01 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openadr.org/DRAS/UtilityDREvent", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.akuacom.pss2.restapi.stubs;
