//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.07 at 12:57:32 PM PST 
//


package com.akuacom.pss2.program.scertp.noaa;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anomalyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="anomalyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="value" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>nonNegativeInteger">
 *                 &lt;attribute name="upper-range" type="{}percentRange" />
 *                 &lt;attribute name="lower-range" type="{}percentRange" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="average temperature above normal"/>
 *             &lt;enumeration value="average temperature below normal"/>
 *             &lt;enumeration value="average precipitation above normal"/>
 *             &lt;enumeration value="average precipitation below normal"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" fixed="percent" />
 *       &lt;attribute name="time-layout" use="required" type="{}time-layoutAttributeType" />
 *       &lt;attribute name="categorical-table" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="conversion-table" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "anomalyType", propOrder = {
    "name",
    "value"
})
public class AnomalyType {

    protected String name;
    @XmlElement(nillable = true)
    protected List<AnomalyType.Value> value;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "units")
    protected String units;
    @XmlAttribute(name = "time-layout", required = true)
    protected String timeLayout;
    @XmlAttribute(name = "categorical-table")
    protected String categoricalTable;
    @XmlAttribute(name = "conversion-table")
    protected String conversionTable;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the value property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnomalyType.Value }
     * 
     * 
     */
    public List<AnomalyType.Value> getValue() {
        if (value == null) {
            value = new ArrayList<AnomalyType.Value>();
        }
        return this.value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnits() {
        if (units == null) {
            return "percent";
        } else {
            return units;
        }
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnits(String value) {
        this.units = value;
    }

    /**
     * Gets the value of the timeLayout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeLayout() {
        return timeLayout;
    }

    /**
     * Sets the value of the timeLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeLayout(String value) {
        this.timeLayout = value;
    }

    /**
     * Gets the value of the categoricalTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoricalTable() {
        return categoricalTable;
    }

    /**
     * Sets the value of the categoricalTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoricalTable(String value) {
        this.categoricalTable = value;
    }

    /**
     * Gets the value of the conversionTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConversionTable() {
        return conversionTable;
    }

    /**
     * Sets the value of the conversionTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConversionTable(String value) {
        this.conversionTable = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>nonNegativeInteger">
     *       &lt;attribute name="upper-range" type="{}percentRange" />
     *       &lt;attribute name="lower-range" type="{}percentRange" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Value {

        @XmlValue
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger value;
        @XmlAttribute(name = "upper-range")
        protected Integer upperRange;
        @XmlAttribute(name = "lower-range")
        protected Integer lowerRange;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

        /**
         * Gets the value of the upperRange property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getUpperRange() {
            return upperRange;
        }

        /**
         * Sets the value of the upperRange property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setUpperRange(Integer value) {
            this.upperRange = value;
        }

        /**
         * Gets the value of the lowerRange property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getLowerRange() {
            return lowerRange;
        }

        /**
         * Sets the value of the lowerRange property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setLowerRange(Integer value) {
            this.lowerRange = value;
        }

    }

}
