/*
 * www.akuacom.com - Automating Demand Response
 * 
 * com.akuacom.pss2.program.scertp.noaa.CurrentObservation.java - Copyright(c)1994 to 2010 by Akuacom . All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification, is prohibited.
 *
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.29 at 06:03:51 PM CST 
//


package com.akuacom.pss2.program.scertp.noaa;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="credit" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 * &lt;element name="credit_URL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 * &lt;element name="image" type="{}imageType" minOccurs="0"/>
 * &lt;element name="suggested_pickup" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 * &lt;element name="suggested_pickup_period" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 * &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 * &lt;element name="station_id" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 * &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="elevation" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 * &lt;element name="observation_time" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 * &lt;element name="observation_time_rfc822" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 * &lt;element name="weather" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 * &lt;element name="temperature_string" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 * &lt;element name="temp_f" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="temp_c" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="water_temp_f" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="water_temp_c" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="relative_humidity" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 * &lt;element name="wind_string" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 * &lt;element name="wind_dir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="wind_degrees" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 * &lt;element name="wind_mph" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="wind_gust_mph" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="wind_kt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="wind_gust_kt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="pressure_string" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 * &lt;element name="pressure_mb" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="pressure_in" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="pressure_tendency_mb" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="pressure_tendency_in" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="dewpoint_string" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 * &lt;element name="dewpoint_f" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="dewpoint_c" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="heat_index_string" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 * &lt;element name="heat_index_f" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 * &lt;element name="heat_index_c" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 * &lt;element name="windchill_string" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/>
 * &lt;element name="windchill_f" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 * &lt;element name="windchill_c" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 * &lt;element name="visibility_mi" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="wave_height_m" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="wave_height_ft" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="dominant_period_sec" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 * &lt;element name="average_period_sec" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="mean_wave_dir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="mean_wave_degrees" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 * &lt;element name="tide_ft" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="steepness" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="water_column_height" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 * &lt;element name="surf_height_ft" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="swell_dir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="swell_degrees" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 * &lt;element name="swell_period" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="icon_url_base" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 * &lt;element name="icon_name" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 * &lt;element name="two_day_history_url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 * &lt;element name="icon_url_name" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 * &lt;element name="ob_url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 * &lt;element name="disclaimer_url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 * &lt;element name="copyright_url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 * &lt;element name="privacy_policy_url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" default="1.0" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "credit",
    "creditURL",
    "image",
    "suggestedPickup",
    "suggestedPickupPeriod",
    "location",
    "stationId",
    "latitude",
    "longitude",
    "elevation",
    "observationTime",
    "observationTimeRfc822",
    "weather",
    "temperatureString",
    "tempF",
    "tempC",
    "waterTempF",
    "waterTempC",
    "relativeHumidity",
    "windString",
    "windDir",
    "windDegrees",
    "windMph",
    "windGustMph",
    "windKt",
    "windGustKt",
    "pressureString",
    "pressureMb",
    "pressureIn",
    "pressureTendencyMb",
    "pressureTendencyIn",
    "dewpointString",
    "dewpointF",
    "dewpointC",
    "heatIndexString",
    "heatIndexF",
    "heatIndexC",
    "windchillString",
    "windchillF",
    "windchillC",
    "visibilityMi",
    "waveHeightM",
    "waveHeightFt",
    "dominantPeriodSec",
    "averagePeriodSec",
    "meanWaveDir",
    "meanWaveDegrees",
    "tideFt",
    "steepness",
    "waterColumnHeight",
    "surfHeightFt",
    "swellDir",
    "swellDegrees",
    "swellPeriod",
    "iconUrlBase",
    "iconName",
    "twoDayHistoryUrl",
    "iconUrlName",
    "obUrl",
    "disclaimerUrl",
    "copyrightUrl",
    "privacyPolicyUrl"
})
@XmlRootElement(name = "current_observation")
public class CurrentObservation {

    /** The credit. */
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String credit;
    
    /** The credit url. */
    @XmlElement(name = "credit_URL")
    @XmlSchemaType(name = "anyURI")
    protected String creditURL;
    
    /** The image. */
    protected ImageType image;
    
    /** The suggested pickup. */
    @XmlElement(name = "suggested_pickup")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String suggestedPickup;
    
    /** The suggested pickup period. */
    @XmlElement(name = "suggested_pickup_period")
    protected BigInteger suggestedPickupPeriod;
    
    /** The location. */
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String location;
    
    /** The station id. */
    @XmlElement(name = "station_id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String stationId;
    
    /** The latitude. */
    protected String latitude;
    
    /** The longitude. */
    protected String longitude;
    
    /** The elevation. */
    protected BigInteger elevation;
    
    /** The observation time. */
    @XmlElement(name = "observation_time")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String observationTime;
    
    /** The observation time rfc822. */
    @XmlElement(name = "observation_time_rfc822")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String observationTimeRfc822;
    
    /** The weather. */
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String weather;
    
    /** The temperature string. */
    @XmlElement(name = "temperature_string")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String temperatureString;
    
    /** The temp f. */
    @XmlElement(name = "temp_f")
    protected BigDecimal tempF;
    
    /** The temp c. */
    @XmlElement(name = "temp_c")
    protected BigDecimal tempC;
    
    /** The water temp f. */
    @XmlElement(name = "water_temp_f")
    protected BigDecimal waterTempF;
    
    /** The water temp c. */
    @XmlElement(name = "water_temp_c")
    protected BigDecimal waterTempC;
    
    /** The relative humidity. */
    @XmlElement(name = "relative_humidity")
    protected BigInteger relativeHumidity;
    
    /** The wind string. */
    @XmlElement(name = "wind_string")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String windString;
    
    /** The wind dir. */
    @XmlElement(name = "wind_dir")
    protected String windDir;
    
    /** The wind degrees. */
    @XmlElement(name = "wind_degrees")
    protected BigInteger windDegrees;
    
    /** The wind mph. */
    @XmlElement(name = "wind_mph")
    protected BigDecimal windMph;
    
    /** The wind gust mph. */
    @XmlElement(name = "wind_gust_mph")
    protected BigDecimal windGustMph;
    
    /** The wind kt. */
    @XmlElement(name = "wind_kt")
    protected BigDecimal windKt;
    
    /** The wind gust kt. */
    @XmlElement(name = "wind_gust_kt")
    protected BigDecimal windGustKt;
    
    /** The pressure string. */
    @XmlElement(name = "pressure_string")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String pressureString;
    
    /** The pressure mb. */
    @XmlElement(name = "pressure_mb")
    protected BigDecimal pressureMb;
    
    /** The pressure in. */
    @XmlElement(name = "pressure_in")
    protected BigDecimal pressureIn;
    
    /** The pressure tendency mb. */
    @XmlElement(name = "pressure_tendency_mb")
    protected BigDecimal pressureTendencyMb;
    
    /** The pressure tendency in. */
    @XmlElement(name = "pressure_tendency_in")
    protected BigDecimal pressureTendencyIn;
    
    /** The dewpoint string. */
    @XmlElement(name = "dewpoint_string")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String dewpointString;
    
    /** The dewpoint f. */
    @XmlElement(name = "dewpoint_f")
    protected BigDecimal dewpointF;
    
    /** The dewpoint c. */
    @XmlElement(name = "dewpoint_c")
    protected BigDecimal dewpointC;
    
    /** The heat index string. */
    @XmlElement(name = "heat_index_string")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String heatIndexString;
    
    /** The heat index f. */
    @XmlElement(name = "heat_index_f")
    protected BigInteger heatIndexF;
    
    /** The heat index c. */
    @XmlElement(name = "heat_index_c")
    protected BigInteger heatIndexC;
    
    /** The windchill string. */
    @XmlElement(name = "windchill_string")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String windchillString;
    
    /** The windchill f. */
    @XmlElement(name = "windchill_f")
    protected BigInteger windchillF;
    
    /** The windchill c. */
    @XmlElement(name = "windchill_c")
    protected BigInteger windchillC;
    
    /** The visibility mi. */
    @XmlElement(name = "visibility_mi")
    protected BigDecimal visibilityMi;
    
    /** The wave height m. */
    @XmlElement(name = "wave_height_m")
    protected BigDecimal waveHeightM;
    
    /** The wave height ft. */
    @XmlElement(name = "wave_height_ft")
    protected BigDecimal waveHeightFt;
    
    /** The dominant period sec. */
    @XmlElement(name = "dominant_period_sec")
    protected BigInteger dominantPeriodSec;
    
    /** The average period sec. */
    @XmlElement(name = "average_period_sec")
    protected BigDecimal averagePeriodSec;
    
    /** The mean wave dir. */
    @XmlElement(name = "mean_wave_dir")
    protected String meanWaveDir;
    
    /** The mean wave degrees. */
    @XmlElement(name = "mean_wave_degrees")
    protected BigInteger meanWaveDegrees;
    
    /** The tide ft. */
    @XmlElement(name = "tide_ft")
    protected BigDecimal tideFt;
    
    /** The steepness. */
    protected String steepness;
    
    /** The water column height. */
    @XmlElement(name = "water_column_height")
    protected BigDecimal waterColumnHeight;
    
    /** The surf height ft. */
    @XmlElement(name = "surf_height_ft")
    protected String surfHeightFt;
    
    /** The swell dir. */
    @XmlElement(name = "swell_dir")
    protected String swellDir;
    
    /** The swell degrees. */
    @XmlElement(name = "swell_degrees")
    protected BigInteger swellDegrees;
    
    /** The swell period. */
    @XmlElement(name = "swell_period")
    protected String swellPeriod;
    
    /** The icon url base. */
    @XmlElement(name = "icon_url_base")
    @XmlSchemaType(name = "anyURI")
    protected String iconUrlBase;
    
    /** The icon name. */
    @XmlElement(name = "icon_name")
    @XmlSchemaType(name = "anyURI")
    protected String iconName;
    
    /** The two day history url. */
    @XmlElement(name = "two_day_history_url")
    @XmlSchemaType(name = "anyURI")
    protected String twoDayHistoryUrl;
    
    /** The icon url name. */
    @XmlElement(name = "icon_url_name")
    @XmlSchemaType(name = "anyURI")
    protected String iconUrlName;
    
    /** The ob url. */
    @XmlElement(name = "ob_url")
    @XmlSchemaType(name = "anyURI")
    protected String obUrl;
    
    /** The disclaimer url. */
    @XmlElement(name = "disclaimer_url")
    @XmlSchemaType(name = "anyURI")
    protected String disclaimerUrl;
    
    /** The copyright url. */
    @XmlElement(name = "copyright_url")
    @XmlSchemaType(name = "anyURI")
    protected String copyrightUrl;
    
    /** The privacy policy url. */
    @XmlElement(name = "privacy_policy_url")
    @XmlSchemaType(name = "anyURI")
    protected String privacyPolicyUrl;
    
    /** The version. */
    @XmlAttribute
    protected String version;

    /**
     * Gets the value of the credit property.
     * 
     * @return the credit
     * 
     * possible object is
     * {@link String }
     */
    public String getCredit() {
        return credit;
    }

    /**
     * Sets the value of the credit property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setCredit(String value) {
        this.credit = value;
    }

    /**
     * Gets the value of the creditURL property.
     * 
     * @return the credit url
     * 
     * possible object is
     * {@link String }
     */
    public String getCreditURL() {
        return creditURL;
    }

    /**
     * Sets the value of the creditURL property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setCreditURL(String value) {
        this.creditURL = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return the image
     * 
     * possible object is
     * {@link ImageType }
     */
    public ImageType getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value allowed object is
     * {@link ImageType }
     */
    public void setImage(ImageType value) {
        this.image = value;
    }

    /**
     * Gets the value of the suggestedPickup property.
     * 
     * @return the suggested pickup
     * 
     * possible object is
     * {@link String }
     */
    public String getSuggestedPickup() {
        return suggestedPickup;
    }

    /**
     * Sets the value of the suggestedPickup property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setSuggestedPickup(String value) {
        this.suggestedPickup = value;
    }

    /**
     * Gets the value of the suggestedPickupPeriod property.
     * 
     * @return the suggested pickup period
     * 
     * possible object is
     * {@link BigInteger }
     */
    public BigInteger getSuggestedPickupPeriod() {
        return suggestedPickupPeriod;
    }

    /**
     * Sets the value of the suggestedPickupPeriod property.
     * 
     * @param value allowed object is
     * {@link BigInteger }
     */
    public void setSuggestedPickupPeriod(BigInteger value) {
        this.suggestedPickupPeriod = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return the location
     * 
     * possible object is
     * {@link String }
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the stationId property.
     * 
     * @return the station id
     * 
     * possible object is
     * {@link String }
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * Sets the value of the stationId property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setStationId(String value) {
        this.stationId = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return the latitude
     * 
     * possible object is
     * {@link String }
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setLatitude(String value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return the longitude
     * 
     * possible object is
     * {@link String }
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setLongitude(String value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the elevation property.
     * 
     * @return the elevation
     * 
     * possible object is
     * {@link BigInteger }
     */
    public BigInteger getElevation() {
        return elevation;
    }

    /**
     * Sets the value of the elevation property.
     * 
     * @param value allowed object is
     * {@link BigInteger }
     */
    public void setElevation(BigInteger value) {
        this.elevation = value;
    }

    /**
     * Gets the value of the observationTime property.
     * 
     * @return the observation time
     * 
     * possible object is
     * {@link String }
     */
    public String getObservationTime() {
        return observationTime;
    }

    /**
     * Sets the value of the observationTime property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setObservationTime(String value) {
        this.observationTime = value;
    }

    /**
     * Gets the value of the observationTimeRfc822 property.
     * 
     * @return the observation time rfc822
     * 
     * possible object is
     * {@link String }
     */
    public String getObservationTimeRfc822() {
        return observationTimeRfc822;
    }

    /**
     * Sets the value of the observationTimeRfc822 property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setObservationTimeRfc822(String value) {
        this.observationTimeRfc822 = value;
    }

    /**
     * Gets the value of the weather property.
     * 
     * @return the weather
     * 
     * possible object is
     * {@link String }
     */
    public String getWeather() {
        return weather;
    }

    /**
     * Sets the value of the weather property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setWeather(String value) {
        this.weather = value;
    }

    /**
     * Gets the value of the temperatureString property.
     * 
     * @return the temperature string
     * 
     * possible object is
     * {@link String }
     */
    public String getTemperatureString() {
        return temperatureString;
    }

    /**
     * Sets the value of the temperatureString property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setTemperatureString(String value) {
        this.temperatureString = value;
    }

    /**
     * Gets the value of the tempF property.
     * 
     * @return the temp f
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getTempF() {
        return tempF;
    }

    /**
     * Sets the value of the tempF property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setTempF(BigDecimal value) {
        this.tempF = value;
    }

    /**
     * Gets the value of the tempC property.
     * 
     * @return the temp c
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getTempC() {
        return tempC;
    }

    /**
     * Sets the value of the tempC property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setTempC(BigDecimal value) {
        this.tempC = value;
    }

    /**
     * Gets the value of the waterTempF property.
     * 
     * @return the water temp f
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getWaterTempF() {
        return waterTempF;
    }

    /**
     * Sets the value of the waterTempF property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setWaterTempF(BigDecimal value) {
        this.waterTempF = value;
    }

    /**
     * Gets the value of the waterTempC property.
     * 
     * @return the water temp c
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getWaterTempC() {
        return waterTempC;
    }

    /**
     * Sets the value of the waterTempC property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setWaterTempC(BigDecimal value) {
        this.waterTempC = value;
    }

    /**
     * Gets the value of the relativeHumidity property.
     * 
     * @return the relative humidity
     * 
     * possible object is
     * {@link BigInteger }
     */
    public BigInteger getRelativeHumidity() {
        return relativeHumidity;
    }

    /**
     * Sets the value of the relativeHumidity property.
     * 
     * @param value allowed object is
     * {@link BigInteger }
     */
    public void setRelativeHumidity(BigInteger value) {
        this.relativeHumidity = value;
    }

    /**
     * Gets the value of the windString property.
     * 
     * @return the wind string
     * 
     * possible object is
     * {@link String }
     */
    public String getWindString() {
        return windString;
    }

    /**
     * Sets the value of the windString property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setWindString(String value) {
        this.windString = value;
    }

    /**
     * Gets the value of the windDir property.
     * 
     * @return the wind dir
     * 
     * possible object is
     * {@link String }
     */
    public String getWindDir() {
        return windDir;
    }

    /**
     * Sets the value of the windDir property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setWindDir(String value) {
        this.windDir = value;
    }

    /**
     * Gets the value of the windDegrees property.
     * 
     * @return the wind degrees
     * 
     * possible object is
     * {@link BigInteger }
     */
    public BigInteger getWindDegrees() {
        return windDegrees;
    }

    /**
     * Sets the value of the windDegrees property.
     * 
     * @param value allowed object is
     * {@link BigInteger }
     */
    public void setWindDegrees(BigInteger value) {
        this.windDegrees = value;
    }

    /**
     * Gets the value of the windMph property.
     * 
     * @return the wind mph
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getWindMph() {
        return windMph;
    }

    /**
     * Sets the value of the windMph property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setWindMph(BigDecimal value) {
        this.windMph = value;
    }

    /**
     * Gets the value of the windGustMph property.
     * 
     * @return the wind gust mph
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getWindGustMph() {
        return windGustMph;
    }

    /**
     * Sets the value of the windGustMph property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setWindGustMph(BigDecimal value) {
        this.windGustMph = value;
    }

    /**
     * Gets the value of the windKt property.
     * 
     * @return the wind kt
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getWindKt() {
        return windKt;
    }

    /**
     * Sets the value of the windKt property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setWindKt(BigDecimal value) {
        this.windKt = value;
    }

    /**
     * Gets the value of the windGustKt property.
     * 
     * @return the wind gust kt
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getWindGustKt() {
        return windGustKt;
    }

    /**
     * Sets the value of the windGustKt property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setWindGustKt(BigDecimal value) {
        this.windGustKt = value;
    }

    /**
     * Gets the value of the pressureString property.
     * 
     * @return the pressure string
     * 
     * possible object is
     * {@link String }
     */
    public String getPressureString() {
        return pressureString;
    }

    /**
     * Sets the value of the pressureString property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setPressureString(String value) {
        this.pressureString = value;
    }

    /**
     * Gets the value of the pressureMb property.
     * 
     * @return the pressure mb
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getPressureMb() {
        return pressureMb;
    }

    /**
     * Sets the value of the pressureMb property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setPressureMb(BigDecimal value) {
        this.pressureMb = value;
    }

    /**
     * Gets the value of the pressureIn property.
     * 
     * @return the pressure in
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getPressureIn() {
        return pressureIn;
    }

    /**
     * Sets the value of the pressureIn property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setPressureIn(BigDecimal value) {
        this.pressureIn = value;
    }

    /**
     * Gets the value of the pressureTendencyMb property.
     * 
     * @return the pressure tendency mb
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getPressureTendencyMb() {
        return pressureTendencyMb;
    }

    /**
     * Sets the value of the pressureTendencyMb property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setPressureTendencyMb(BigDecimal value) {
        this.pressureTendencyMb = value;
    }

    /**
     * Gets the value of the pressureTendencyIn property.
     * 
     * @return the pressure tendency in
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getPressureTendencyIn() {
        return pressureTendencyIn;
    }

    /**
     * Sets the value of the pressureTendencyIn property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setPressureTendencyIn(BigDecimal value) {
        this.pressureTendencyIn = value;
    }

    /**
     * Gets the value of the dewpointString property.
     * 
     * @return the dewpoint string
     * 
     * possible object is
     * {@link String }
     */
    public String getDewpointString() {
        return dewpointString;
    }

    /**
     * Sets the value of the dewpointString property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setDewpointString(String value) {
        this.dewpointString = value;
    }

    /**
     * Gets the value of the dewpointF property.
     * 
     * @return the dewpoint f
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getDewpointF() {
        return dewpointF;
    }

    /**
     * Sets the value of the dewpointF property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setDewpointF(BigDecimal value) {
        this.dewpointF = value;
    }

    /**
     * Gets the value of the dewpointC property.
     * 
     * @return the dewpoint c
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getDewpointC() {
        return dewpointC;
    }

    /**
     * Sets the value of the dewpointC property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setDewpointC(BigDecimal value) {
        this.dewpointC = value;
    }

    /**
     * Gets the value of the heatIndexString property.
     * 
     * @return the heat index string
     * 
     * possible object is
     * {@link String }
     */
    public String getHeatIndexString() {
        return heatIndexString;
    }

    /**
     * Sets the value of the heatIndexString property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setHeatIndexString(String value) {
        this.heatIndexString = value;
    }

    /**
     * Gets the value of the heatIndexF property.
     * 
     * @return the heat index f
     * 
     * possible object is
     * {@link BigInteger }
     */
    public BigInteger getHeatIndexF() {
        return heatIndexF;
    }

    /**
     * Sets the value of the heatIndexF property.
     * 
     * @param value allowed object is
     * {@link BigInteger }
     */
    public void setHeatIndexF(BigInteger value) {
        this.heatIndexF = value;
    }

    /**
     * Gets the value of the heatIndexC property.
     * 
     * @return the heat index c
     * 
     * possible object is
     * {@link BigInteger }
     */
    public BigInteger getHeatIndexC() {
        return heatIndexC;
    }

    /**
     * Sets the value of the heatIndexC property.
     * 
     * @param value allowed object is
     * {@link BigInteger }
     */
    public void setHeatIndexC(BigInteger value) {
        this.heatIndexC = value;
    }

    /**
     * Gets the value of the windchillString property.
     * 
     * @return the windchill string
     * 
     * possible object is
     * {@link String }
     */
    public String getWindchillString() {
        return windchillString;
    }

    /**
     * Sets the value of the windchillString property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setWindchillString(String value) {
        this.windchillString = value;
    }

    /**
     * Gets the value of the windchillF property.
     * 
     * @return the windchill f
     * 
     * possible object is
     * {@link BigInteger }
     */
    public BigInteger getWindchillF() {
        return windchillF;
    }

    /**
     * Sets the value of the windchillF property.
     * 
     * @param value allowed object is
     * {@link BigInteger }
     */
    public void setWindchillF(BigInteger value) {
        this.windchillF = value;
    }

    /**
     * Gets the value of the windchillC property.
     * 
     * @return the windchill c
     * 
     * possible object is
     * {@link BigInteger }
     */
    public BigInteger getWindchillC() {
        return windchillC;
    }

    /**
     * Sets the value of the windchillC property.
     * 
     * @param value allowed object is
     * {@link BigInteger }
     */
    public void setWindchillC(BigInteger value) {
        this.windchillC = value;
    }

    /**
     * Gets the value of the visibilityMi property.
     * 
     * @return the visibility mi
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getVisibilityMi() {
        return visibilityMi;
    }

    /**
     * Sets the value of the visibilityMi property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setVisibilityMi(BigDecimal value) {
        this.visibilityMi = value;
    }

    /**
     * Gets the value of the waveHeightM property.
     * 
     * @return the wave height m
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getWaveHeightM() {
        return waveHeightM;
    }

    /**
     * Sets the value of the waveHeightM property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setWaveHeightM(BigDecimal value) {
        this.waveHeightM = value;
    }

    /**
     * Gets the value of the waveHeightFt property.
     * 
     * @return the wave height ft
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getWaveHeightFt() {
        return waveHeightFt;
    }

    /**
     * Sets the value of the waveHeightFt property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setWaveHeightFt(BigDecimal value) {
        this.waveHeightFt = value;
    }

    /**
     * Gets the value of the dominantPeriodSec property.
     * 
     * @return the dominant period sec
     * 
     * possible object is
     * {@link BigInteger }
     */
    public BigInteger getDominantPeriodSec() {
        return dominantPeriodSec;
    }

    /**
     * Sets the value of the dominantPeriodSec property.
     * 
     * @param value allowed object is
     * {@link BigInteger }
     */
    public void setDominantPeriodSec(BigInteger value) {
        this.dominantPeriodSec = value;
    }

    /**
     * Gets the value of the averagePeriodSec property.
     * 
     * @return the average period sec
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getAveragePeriodSec() {
        return averagePeriodSec;
    }

    /**
     * Sets the value of the averagePeriodSec property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setAveragePeriodSec(BigDecimal value) {
        this.averagePeriodSec = value;
    }

    /**
     * Gets the value of the meanWaveDir property.
     * 
     * @return the mean wave dir
     * 
     * possible object is
     * {@link String }
     */
    public String getMeanWaveDir() {
        return meanWaveDir;
    }

    /**
     * Sets the value of the meanWaveDir property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setMeanWaveDir(String value) {
        this.meanWaveDir = value;
    }

    /**
     * Gets the value of the meanWaveDegrees property.
     * 
     * @return the mean wave degrees
     * 
     * possible object is
     * {@link BigInteger }
     */
    public BigInteger getMeanWaveDegrees() {
        return meanWaveDegrees;
    }

    /**
     * Sets the value of the meanWaveDegrees property.
     * 
     * @param value allowed object is
     * {@link BigInteger }
     */
    public void setMeanWaveDegrees(BigInteger value) {
        this.meanWaveDegrees = value;
    }

    /**
     * Gets the value of the tideFt property.
     * 
     * @return the tide ft
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getTideFt() {
        return tideFt;
    }

    /**
     * Sets the value of the tideFt property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setTideFt(BigDecimal value) {
        this.tideFt = value;
    }

    /**
     * Gets the value of the steepness property.
     * 
     * @return the steepness
     * 
     * possible object is
     * {@link String }
     */
    public String getSteepness() {
        return steepness;
    }

    /**
     * Sets the value of the steepness property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setSteepness(String value) {
        this.steepness = value;
    }

    /**
     * Gets the value of the waterColumnHeight property.
     * 
     * @return the water column height
     * 
     * possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getWaterColumnHeight() {
        return waterColumnHeight;
    }

    /**
     * Sets the value of the waterColumnHeight property.
     * 
     * @param value allowed object is
     * {@link BigDecimal }
     */
    public void setWaterColumnHeight(BigDecimal value) {
        this.waterColumnHeight = value;
    }

    /**
     * Gets the value of the surfHeightFt property.
     * 
     * @return the surf height ft
     * 
     * possible object is
     * {@link String }
     */
    public String getSurfHeightFt() {
        return surfHeightFt;
    }

    /**
     * Sets the value of the surfHeightFt property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setSurfHeightFt(String value) {
        this.surfHeightFt = value;
    }

    /**
     * Gets the value of the swellDir property.
     * 
     * @return the swell dir
     * 
     * possible object is
     * {@link String }
     */
    public String getSwellDir() {
        return swellDir;
    }

    /**
     * Sets the value of the swellDir property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setSwellDir(String value) {
        this.swellDir = value;
    }

    /**
     * Gets the value of the swellDegrees property.
     * 
     * @return the swell degrees
     * 
     * possible object is
     * {@link BigInteger }
     */
    public BigInteger getSwellDegrees() {
        return swellDegrees;
    }

    /**
     * Sets the value of the swellDegrees property.
     * 
     * @param value allowed object is
     * {@link BigInteger }
     */
    public void setSwellDegrees(BigInteger value) {
        this.swellDegrees = value;
    }

    /**
     * Gets the value of the swellPeriod property.
     * 
     * @return the swell period
     * 
     * possible object is
     * {@link String }
     */
    public String getSwellPeriod() {
        return swellPeriod;
    }

    /**
     * Sets the value of the swellPeriod property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setSwellPeriod(String value) {
        this.swellPeriod = value;
    }

    /**
     * Gets the value of the iconUrlBase property.
     * 
     * @return the icon url base
     * 
     * possible object is
     * {@link String }
     */
    public String getIconUrlBase() {
        return iconUrlBase;
    }

    /**
     * Sets the value of the iconUrlBase property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setIconUrlBase(String value) {
        this.iconUrlBase = value;
    }

    /**
     * Gets the value of the iconName property.
     * 
     * @return the icon name
     * 
     * possible object is
     * {@link String }
     */
    public String getIconName() {
        return iconName;
    }

    /**
     * Sets the value of the iconName property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setIconName(String value) {
        this.iconName = value;
    }

    /**
     * Gets the value of the twoDayHistoryUrl property.
     * 
     * @return the two day history url
     * 
     * possible object is
     * {@link String }
     */
    public String getTwoDayHistoryUrl() {
        return twoDayHistoryUrl;
    }

    /**
     * Sets the value of the twoDayHistoryUrl property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setTwoDayHistoryUrl(String value) {
        this.twoDayHistoryUrl = value;
    }

    /**
     * Gets the value of the iconUrlName property.
     * 
     * @return the icon url name
     * 
     * possible object is
     * {@link String }
     */
    public String getIconUrlName() {
        return iconUrlName;
    }

    /**
     * Sets the value of the iconUrlName property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setIconUrlName(String value) {
        this.iconUrlName = value;
    }

    /**
     * Gets the value of the obUrl property.
     * 
     * @return the ob url
     * 
     * possible object is
     * {@link String }
     */
    public String getObUrl() {
        return obUrl;
    }

    /**
     * Sets the value of the obUrl property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setObUrl(String value) {
        this.obUrl = value;
    }

    /**
     * Gets the value of the disclaimerUrl property.
     * 
     * @return the disclaimer url
     * 
     * possible object is
     * {@link String }
     */
    public String getDisclaimerUrl() {
        return disclaimerUrl;
    }

    /**
     * Sets the value of the disclaimerUrl property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setDisclaimerUrl(String value) {
        this.disclaimerUrl = value;
    }

    /**
     * Gets the value of the copyrightUrl property.
     * 
     * @return the copyright url
     * 
     * possible object is
     * {@link String }
     */
    public String getCopyrightUrl() {
        return copyrightUrl;
    }

    /**
     * Sets the value of the copyrightUrl property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setCopyrightUrl(String value) {
        this.copyrightUrl = value;
    }

    /**
     * Gets the value of the privacyPolicyUrl property.
     * 
     * @return the privacy policy url
     * 
     * possible object is
     * {@link String }
     */
    public String getPrivacyPolicyUrl() {
        return privacyPolicyUrl;
    }

    /**
     * Sets the value of the privacyPolicyUrl property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setPrivacyPolicyUrl(String value) {
        this.privacyPolicyUrl = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return the version
     * 
     * possible object is
     * {@link String }
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value allowed object is
     * {@link String }
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
