//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.07 at 12:57:32 PM PST 
//


package com.akuacom.pss2.program.scertp.noaa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for locationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="locationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="location-key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="point" type="{}pointType" minOccurs="0"/>
 *           &lt;element name="nws-zone" type="{}nws-zoneType" minOccurs="0"/>
 *           &lt;element name="area" type="{}areaType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="city" type="{}cityType" minOccurs="0"/>
 *         &lt;element name="area-description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="height" type="{}heightType" minOccurs="0"/>
 *           &lt;element name="level" type="{}levelType" minOccurs="0"/>
 *           &lt;element name="layer" type="{}layerType" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "locationType", propOrder = {
    "locationKey",
    "description",
    "point",
    "nwsZone",
    "area",
    "city",
    "areaDescription",
    "height",
    "level",
    "layer"
})
public class LocationType {

    @XmlElement(name = "location-key", required = true)
    protected String locationKey;
    protected String description;
    protected PointType point;
    @XmlElement(name = "nws-zone")
    protected NwsZoneType nwsZone;
    protected AreaType area;
    protected CityType city;
    @XmlElement(name = "area-description")
    protected String areaDescription;
    protected HeightType height;
    protected LevelType level;
    protected LayerType layer;

    /**
     * Gets the value of the locationKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationKey() {
        return locationKey;
    }

    /**
     * Sets the value of the locationKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationKey(String value) {
        this.locationKey = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the point property.
     * 
     * @return
     *     possible object is
     *     {@link PointType }
     *     
     */
    public PointType getPoint() {
        return point;
    }

    /**
     * Sets the value of the point property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointType }
     *     
     */
    public void setPoint(PointType value) {
        this.point = value;
    }

    /**
     * Gets the value of the nwsZone property.
     * 
     * @return
     *     possible object is
     *     {@link NwsZoneType }
     *     
     */
    public NwsZoneType getNwsZone() {
        return nwsZone;
    }

    /**
     * Sets the value of the nwsZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link NwsZoneType }
     *     
     */
    public void setNwsZone(NwsZoneType value) {
        this.nwsZone = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link AreaType }
     *     
     */
    public AreaType getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaType }
     *     
     */
    public void setArea(AreaType value) {
        this.area = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link CityType }
     *     
     */
    public CityType getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link CityType }
     *     
     */
    public void setCity(CityType value) {
        this.city = value;
    }

    /**
     * Gets the value of the areaDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaDescription() {
        return areaDescription;
    }

    /**
     * Sets the value of the areaDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaDescription(String value) {
        this.areaDescription = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link HeightType }
     *     
     */
    public HeightType getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeightType }
     *     
     */
    public void setHeight(HeightType value) {
        this.height = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link LevelType }
     *     
     */
    public LevelType getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelType }
     *     
     */
    public void setLevel(LevelType value) {
        this.level = value;
    }

    /**
     * Gets the value of the layer property.
     * 
     * @return
     *     possible object is
     *     {@link LayerType }
     *     
     */
    public LayerType getLayer() {
        return layer;
    }

    /**
     * Sets the value of the layer property.
     * 
     * @param value
     *     allowed object is
     *     {@link LayerType }
     *     
     */
    public void setLayer(LayerType value) {
        this.layer = value;
    }

}
