package com.honeywell.dras.vtn.api;

public interface Request {
	
	public Long getReplyLimit();
	
	// generated by VEN (the requester)
	public String getRequestId();
	
	public String getVenID();
	
	

}
